---
# Project Information
site_name: test-cookiecutter-pypackage-project
site_author: Marco Gancitano
site_description: A test project for my cookiecutter-pypackage repo

# Repository information
repo_name: mgancita/test_cookiecutter_pypackage_project
repo_url: https://github.com/mgancita/test_cookiecutter_pypackage_project
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Marco Gancitano

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mgancita
      name: mgancita on GitHub

# Page tree
nav:
  - Home: index.md
